name: CI

on:
  push:
    branches: ["**"]
  pull_request:
  workflow_dispatch:
    inputs:
      run_mobile:
        description: "Run mobile tests (requires self-hosted Android runner with device/emulator + Appium)"
        required: false
        type: boolean
        default: false

jobs:
  api-mock:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt

      - name: Run API tests (mock)
        env:
          REQRES_USE_MOCK: 'true'
        run: |
          pytest -m "api and not api_live" -q

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Allure CLI
        run: npm i -g allure-commandline

      - name: Generate Allure report
        run: allure generate allure-results --clean -o allure-report

      - name: Upload Allure report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report

      - name: Upload Allure results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results

  mobile:
    if: ${{ inputs.run_mobile == true }}
    runs-on: [self-hosted, android]
    needs: api-mock
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt

      - name: Run Mobile tests (requires device + Appium)
        env:
          APPIUM_SERVER_URL: ${{ secrets.APPIUM_SERVER_URL }}
          DEVICE_NAME: ${{ secrets.DEVICE_NAME }}
          ANDROID_SERIAL: ${{ secrets.ANDROID_SERIAL }}
        run: |
          pytest tests/mobile -q

      - name: Upload Allure results (mobile)
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-mobile
          path: allure-results
